# Define the stages.
stages:
  # Create a static code analysis stage.
  - analyze

analysis:ec:
  # Add to the analysis stage.
  stage: analyze
  # Use the latest ec Docker image.
  image: mstruebing/editorconfig-checker:latest
  script:
    # Check that all text complies with the EditorConfig file.
    - ec

analysis:flake8:
  # Add to the analysis stage.
  stage: analyze
  # Use the latest flake8 Docker image.
  image:
    name: alpine/flake8:latest
    entrypoint: [""]
  rules:
    - changes:
        - scripts/*.py
  script:
    # Lint the Python code.
    - flake8 scripts/*.py
